server:
  port: 8899
spring:
  jackson:
    time-zone: GMT+8
  application:
    name: campus
  datasource:
#    url: jdbc:h2:mem:h2test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:file:~/.h2/campus;AUTO_SERVER=TRUE
    platform: h2
    username: sa
    password: 123456
    driverClassName: org.h2.Driver
#    url: jdbc:mysql://localhost:3306/campus?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: 123456

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        jdbc:
#          time_zone: UTC-8
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: true
logging:
  level:
    com:
      fosu:
        campus:
          repository: debug  # 打印数据库日记


